services:
  - type: web
    name: carta-timbrada-app
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y libreoffice
      pip install -r requirements.txt
    startCommand: gunicorn api2:app --bind 0.0.0.0:$PORT
